export const legalPages = [
  {
    path: '/hr/impressum',
    title: 'Impresum | MINO Consulting KG',
    metaDescription: 'Impresum društva MINO Consulting KG u Beču s kontaktnim podacima, podacima o društvu i pravnim informacijama.',
    h1: 'Impresum',
    intro: 'Objava podataka u skladu s austrijskim propisima, osobito § 5 ECG-a, § 14 UGB-a i § 25 Mediengesetza.',
    sections: [
      { title: 'Pružatelj usluga i vlasnik medija', items: ['MINO Consulting KG', 'Geblergasse 95/8', '1170 Wien', 'Austrija'] },
      { title: 'Kontakt', items: ['Telefon: +43 1 90 680 200', 'Mobilni telefon: +43 660 21 99 444', 'E-pošta: office@mino-consulting.at', 'Web: www.mino-consulting.at'] },
      { title: 'Sudski registar', items: ['Broj u sudskom registru: FN 157894y', 'Sud: Handelsgericht Wien', 'Pravni oblik: Kommanditgesellschaft', 'Sjedište: Beč', 'Upisano od: 14. lipnja 1997.'] },
      { title: 'PDV identifikacijski broj', items: ['UID: ATU10543606'] },
      { title: 'Neograničeno odgovorni članovi', items: ['Rulas GmbH (upisano 28. travnja 2022.)', 'Mag. Tomislav Siketic'] },
      { title: 'Podaci o reguliranoj profesiji', items: ['Naziv profesije: Steuerberater (porezni savjetnik)', 'Država dodjele: Austrija', 'Profesionalna skupina prema austrijskom Wirtschaftstreuhandberufsgesetzu 2017 (WTBG 2017)'] },
      { title: 'Članstvo', items: ['Kammer der Steuerberater:innen und Wirtschaftsprüfer:innen (KSW)', 'Schönbrunner Straße 222-228 / Stiege 1 / 6. OG', '1120 Wien', 'www.ksw.or.at'] },
      { title: 'Nadzorno tijelo', items: ['Kammer der Steuerberater:innen und Wirtschaftsprüfer:innen (KSW)'] },
      { title: 'Primjenjivi profesionalni propisi', items: ['Wirtschaftstreuhandberufsgesetz 2017 (WTBG 2017)', 'Wirtschaftstreuhandberufs-Ausübungsrichtlinie (WT-ARL)', 'Profesionalna pravila KSW-a', 'Dostupno na: www.ksw.or.at'] },
      { title: 'Rješavanje potrošačkih sporova', items: ['Nismo spremni niti obvezni sudjelovati u postupku mirenja pred tijelom za rješavanje potrošačkih sporova.'] },
      { title: 'Autorsko pravo', items: ['Sadržaj i oblikovanje ove web-stranice zaštićeni su autorskim pravom. Korištenje izvan zakonskih granica zahtijeva prethodnu pisanu suglasnost društva MINO Consulting KG.'] },
      { title: 'Odricanje od odgovornosti', items: ['Unatoč pažljivoj provjeri sadržaja ne preuzimamo odgovornost za sadržaj vanjskih poveznica. Za povezane stranice odgovorni su njihovi pružatelji.'] },
      { title: 'Stanje', items: ['Srpanj 2026.'] },
    ],
  },
  {
    path: '/hr/pravila-privatnosti',
    title: 'Pravila privatnosti | MINO Consulting KG',
    metaDescription: 'Pravila privatnosti društva MINO Consulting KG o pristupu stranici, kontaktu, upitima za termin, Google Mapsu i lokalnim postavkama.',
    h1: 'Pravila privatnosti',
    intro: 'Ove informacije opisuju tehničku obradu osobnih podataka pri posjetu ovoj web-stranici i kontaktiranju društva MINO Consulting KG.',
    tableOfContentsTitle: 'Sadržaj',
    tableOfContentsLabel: 'Sadržaj pravila privatnosti',
    sections: [
      { title: '1. Voditelj obrade', paragraphs: ['Voditelj obrade osobnih podataka na ovoj web-stranici je MINO Consulting KG, Geblergasse 95/8, 1170 Wien, Austrija.'] },
      { title: '2. Kontaktni podaci', paragraphs: ['Za pitanja o privatnosti možete se javiti na office@mino-consulting.at ili telefonom na +43 1 90 680 200.'] },
      { title: '3. Opći pristup stranici i zapisnici poslužitelja', paragraphs: ['Pri otvaranju web-stranice prenose se tehnički potrebni podaci o vezi. To može uključivati IP adresu, vrijeme pristupa, zatraženi sadržaj, referrer te podatke o pregledniku i uređaju.', 'Pružatelj hostinga može takve podatke obraditi u zapisnicima radi isporuke, stabilnosti i sigurnosti stranice. Točan rok čuvanja ovisi o tehničkim i pravnim zahtjevima pružatelja.'] },
      { title: '4. Hosting', paragraphs: ['Web-stranica se objavljuje putem usluge GitHub Pages na adresi ristohajdukovic.github.io/minoconsult. Pružatelj hostinga može obrađivati podatke o vezi i pristupu.', 'Točan naziv pružatelja u pravnom tekstu, ugovorne osnove i čuvanje zapisnika provjerit će se prije konačne pravne potvrde.'] },
      { title: '5. Kontakt telefonom', paragraphs: ['Ako nas kontaktirate telefonom, podatke koje nam priopćite koristimo za obradu upita i potrebnu daljnju komunikaciju. Opseg podataka ovisi o sadržaju razgovora.'] },
      { title: '6. Kontakt e-poštom', paragraphs: ['Ako pošaljete e-poruku, obrađuju se adresa pošiljatelja, sadržaj poruke i ostali podaci koje dostavite radi obrade upita i potrebne daljnje komunikacije.', 'Pružatelj usluge za office@mino-consulting.at i konkretno razdoblje čuvanja još trebaju pravnu i organizacijsku potvrdu.'] },
      { title: '7. Priprema upita za termin putem web-stranice', paragraphs: ['Obrazac iz vaših podataka priprema upit e-poštom. Sami odlučujete hoćete li ga otvoriti u svojoj aplikaciji za e-poštu i poslati. Web-stranica ne prikazuje upit kao potvrđeni termin i ne šalje podatke obrasca u bazu web-stranice.', 'Dok je obrazac otvoren, podaci privremeno postoje u stanju preglednika. Ne pohranjuju se u lokalnu pohranu. Tek kada pošaljete pripremljenu poruku, e-pošta se obrađuje putem sustava e-pošte koje koristite vi i MINO Consulting KG.'] },
      { title: '8. Google Maps nakon izričite privole', paragraphs: ['Ugrađena karta Google Mapsa početno je blokirana. Učitava se tek kada odaberete „Učitaj Google Maps“ ili omogućite Google Maps u postavkama privatnosti.', 'Učitavanjem se uspostavlja veza s Googleom te se Googleu mogu prenijeti tehnički podaci poput IP adrese. Privolu možete povući u postavkama privatnosti; karta se tada odmah uklanja i ostaje blokirana pri budućim posjetima.'] },
      { title: '9. Lokalna pohrana za postavke privatnosti', paragraphs: ['Kada omogućite Google Maps, stranica u lokalnoj pohrani preglednika pod ključem mino_privacy_preferences_v1 sprema samo postavku googleMaps: true. Ona ne sadrži podatke obrasca, osobnu identifikacijsku oznaku ni vrijeme.', 'Kada onemogućite Google Maps, spremljeno dopuštenje se uklanja.'] },
      { title: '10. Lokalno smješteni fontovi', paragraphs: ['Fontovi Abhaya Libre i Figtree isporučuju se izravno s ove web-stranice. Za prikaz fontova ne uspostavlja se veza s Google Fonts ili drugim CDN-om za fontove.'] },
      { title: '11. Lokalno smještene slike', paragraphs: ['Datoteke slika prikazane na stranici isporučuju se lokalno. Pri njihovu učitavanju ne uspostavlja se veza s Unsplashom ili vanjskim CDN-om za slike.'] },
      { title: '12. Vanjske poveznice', paragraphs: ['Web-stranica sadrži poveznice na vanjske usluge, primjerice Google Maps ili KSW. Veza s vanjskim pružateljem nastaje tek kada aktivirate takvu poveznicu. Nakon napuštanja ove stranice vrijede pravila privatnosti odgovarajućeg pružatelja.'] },
      { title: '13. Prava ispitanika', paragraphs: ['Ako su ispunjeni zakonski uvjeti, možete zatražiti pristup, ispravak, brisanje ili ograničenje obrade. Gdje je primjenjivo, možete zatražiti prenosivost podataka ili uložiti prigovor.', 'Danu privolu možete povući u svako doba s učinkom za budućnost. To ne utječe na zakonitost obrade provedene prije povlačenja. Zahtjeve pošaljite na office@mino-consulting.at.'] },
      { title: '14. Pritužba austrijskom tijelu za zaštitu podataka', paragraphs: ['Ako smatrate da obrada vaših osobnih podataka krši propise o zaštiti podataka, možete podnijeti pritužbu austrijskom tijelu za zaštitu podataka (Datenschutzbehörde). Aktualni kontaktni podaci dostupni su na web-stranici tog tijela.'] },
      { title: '15. Sigurnost', paragraphs: ['Za web-stranicu se primjenjuju primjerene tehničke i organizacijske mjere kako bi se podaci, u okviru tehničkih mogućnosti, zaštitili od gubitka, neovlaštenog pristupa i izmjene. Prijenos podataka bez ikakvog rizika nije moguće zajamčiti.'] },
      { title: '16. Izmjene pravila privatnosti', paragraphs: ['Ova pravila privatnosti prilagođavat će se ako se promijene tehničke funkcije, korišteni pružatelji ili pravni zahtjevi. Aktualna verzija dostupna je na ovoj stranici.'] },
      { title: '17. Datum verzije', paragraphs: ['Srpanj 2026.'] },
    ],
  },
];
