export const seoPages = [
  {
    path: '/hr/knjigovodstvo-bec',
    title: 'Knjigovodstvo Beč | MINO Consulting KG',
    metaDescription: 'Tekuće knjigovodstvo u Beču: dokumentacija, bankovne transakcije, UVA i otvorena pitanja. Zatražite prvi razgovor s MINO Consulting KG.',
    eyebrow: 'Knjigovodstvo Beč',
    h1: 'Tekuće knjigovodstvo za poduzeća u Beču',
    intro: 'Tekuće knjigovodstvo obrađuje poslovne događaje na temelju dostavljenih računa i bankovnih podataka. Na prvom razgovoru utvrđujemo postojeću dokumentaciju, otvorena razdoblja i mogući ritam obrade.',
    whoForTitle: 'Uobičajene početne situacije',
    whoFor: ['Potrebno je knjižiti tekuće ulazne i izlazne račune', 'Treba uskladiti bankovne transakcije, blagajnu i otvorene stavke', 'Dokumentacija se predaje neujednačeno ili sa zakašnjenjem', 'Za novu djelatnost treba odrediti knjigovodstveni postupak'],
    includedTitle: 'Što knjigovodstvo može obuhvatiti',
    included: ['Tekuće knjiženje dokumenata i bankovnih promjena', 'Pripremu periodične prijave PDV-a (UVA) i pregled rokova', 'Usklađivanje otvorenih stavki', 'Izvještaje u dogovorenom opsegu i napomene o otvorenim pitanjima'],
    clientProvides: ['Izlazne i ulazne račune te bankovne i blagajničke podatke', 'Relevantne ugovore, dokaze i pravodobne odgovore na pitanja'],
    limitations: ['Opseg i ritam dogovaraju se nakon pregleda početne situacije', 'Potpuna i pravodobna dokumentacija ostaje preduvjet'],
    processTitle: 'Kako izgleda moguća suradnja',
    process: [
      { title: 'Dogovor o dokumentaciji', body: 'Utvrđujemo koji su dokumenti, podaci i pristupi potrebni.' },
      { title: 'Dogovor o predaji', body: 'Određujemo način i rokove predaje prema postojećoj situaciji.' },
      { title: 'Obrada i pitanja', body: 'Poslovni događaji obrađuju se u dogovorenom opsegu, a otvorene točke vraćaju na razjašnjenje.' },
    ],
    faq: [
      { question: 'Koji su dokumenti potrebni za tekuće knjigovodstvo?', answer: 'Uobičajeno su potrebni ulazni i izlazni računi, bankovni izvodi, blagajnički podaci, ugovori i drugi relevantni dokumenti.' },
      { question: 'Može li se knjigovodstvo voditi digitalno?', answer: 'Mogući način predaje ovisi o sustavima i postupku koji MINO i klijent dogovore. Prije početka treba potvrditi konkretan način razmjene.' },
      { question: 'Mogu li mala poduzeća i samostalni poduzetnici poslati upit?', answer: 'Mogu. Može li se preuzeti konkretan angažman, ovisi o opsegu, početnoj situaciji i raspoloživom kapacitetu te se utvrđuje zasebno.' },
    ],
    ctaTitle: 'Razjasnite opseg knjigovodstva',
    ctaBody: 'Na prvom razgovoru utvrđujemo postojeću dokumentaciju, važne rokove i mogući način organizacije tekućeg knjigovodstva.',
    relatedLinkLabel: 'Provjerite knjigovodstvo i predaju dokumentacije',
    related: ['/hr/obracun-placa-bec', '/hr/porezni-savjetnik-bec', '/hr/godisnji-obracun-bec'],
  },
  {
    path: '/hr/porezni-savjetnik-bec',
    title: 'Porezni savjetnik Beč | MINO Consulting KG',
    metaDescription: 'Porezno savjetovanje u Beču za poslovna pitanja, prijave i komunikaciju s austrijskom poreznom upravom (Finanzamt).',
    eyebrow: 'Porezni savjetnik Beč',
    h1: 'Porezno savjetovanje za poslovna pitanja u Beču',
    intro: 'Kod poreznih prijava, pitanja o PDV-u, predujmova ili dopisa porezne uprave važni su konkretne činjenice i potpuna dokumentacija. S MINO-m utvrđujete potrebu za savjetovanjem i mogući opseg.',
    whoForTitle: 'Uobičajeni razlozi za upit',
    whoFor: ['Otvorena pitanja o porezu na dohodak, porezu na dobit ili PDV-u', 'Treba razmotriti poreznu prijavu ili dopis Finanzamta', 'Planirane poslovne promjene mogu imati porezne posljedice', 'Prije osnivanja treba utvrditi prve porezne obveze'],
    includedTitle: 'Moguće teme savjetovanja',
    included: ['Tekuća porezna pitanja i rokovi', 'Pripremu i praćenje poreznih prijava', 'Porezno razmatranje ulaganja ili poslovnih promjena', 'Pripremu komunikacije s Finanzamtom'],
    clientProvides: ['Opis činjenica, pitanja i poznatih rokova', 'Relevantna rješenja, dopise, ugovore, dokumente i izračune'],
    limitations: ['Porezna procjena ovisi o potpunim i točnim podacima', 'Ne obećava se porezni rezultat ni prihvaćanje od strane tijela'],
    processTitle: 'Postupak savjetovanja',
    process: [
      { title: 'Utvrđivanje činjenica', body: 'Pregledavamo pitanje, dokumentaciju i poznate rokove.' },
      { title: 'Porezno razmatranje', body: 'Moguće postupanje objašnjava se na temelju dostavljenih podataka.' },
      { title: 'Dogovor o provedbi', body: 'Prijave ili komunikacija preuzimaju se samo u izričito dogovorenom opsegu.' },
    ],
    faq: [
      { question: 'Kada mi treba porezni savjetnik u Beču?', answer: 'Razgovor može biti koristan kada treba razmotriti poreznu prijavu, PDV, planiranu promjenu ili dopis Finanzamta. Konkretna potreba utvrđuje se prema činjenicama.' },
      { question: 'Pomažete li pri poreznom planiranju?', answer: 'Porezne posljedice planiranih promjena mogu se razmotriti u dogovorenom opsegu. Moguća provjera ovisi o činjenicama i dokumentaciji.' },
      { question: 'Mogu li promijeniti dosadašnjeg poreznog savjetnika?', answer: 'Možete poslati takav upit. Može li i kada MINO preuzeti angažman te što je potrebno za primopredaju, utvrđuje se zasebno.' },
    ],
    ctaTitle: 'Pravodobno razjasnite porezna pitanja',
    ctaBody: 'U prvom razgovoru utvrđujemo pitanje, raspoložive dokumente, poznate rokove i mogući opseg savjetovanja.',
    relatedLinkLabel: 'Razjasnite porezna pitanja i komunikaciju s Finanzamtom',
    related: ['/hr/knjigovodstvo-bec', '/hr/porezno-savjetovanje-poduzetnici-bec', '/hr/godisnji-obracun-bec'],
  },
  {
    path: '/hr/obracun-placa-bec',
    title: 'Obračun plaća Beč | MINO Consulting KG',
    metaDescription: 'Obračun plaća u Beču: matični podaci, mjesečne promjene, obračuni i prijave u dogovorenom opsegu.',
    eyebrow: 'Obračun plaća Beč',
    h1: 'Obračun plaća za poslodavce u Beču',
    intro: 'Za redovit obračun plaća matični podaci i mjesečne promjene moraju biti potpuni i pravodobni. Na prvom razgovoru utvrđujemo broj zaposlenika, raspoložive podatke i mogući postupak predaje.',
    whoForTitle: 'Uobičajene početne situacije',
    whoFor: ['Poduzeće već zapošljava radnike', 'Prvo zaposlenje treba organizacijski pripremiti', 'Mjesečne promjene i odsutnosti treba uredno dostavljati', 'Knjiženja plaća treba uskladiti s tekućim knjigovodstvom'],
    includedTitle: 'Što podrška može obuhvatiti',
    included: ['Pripremu redovitih obračuna plaća', 'Prijave i odjave te potrebne mjesečne prijave', 'Organizaciju matičnih podataka i promjena', 'Usklađivanje s knjigovodstvom i godišnjim obračunom'],
    clientProvides: ['Matične podatke te podatke o plaći, radnom vremenu i početku zaposlenja', 'Mjesečne promjene prije dogovorenog roka obračuna'],
    limitations: ['Zakašnjeli ili nepotpuni podaci mogu spriječiti obračun', 'Radnopravno savjetovanje nije automatski dio ove usluge'],
    processTitle: 'Kako se organizira obračun plaća',
    process: [
      { title: 'Preuzimanje podataka', body: 'Utvrđujemo matične podatke, zaposlenje i postojeću dokumentaciju.' },
      { title: 'Mjesečne promjene', body: 'Klijent dostavlja sate, odsutnosti i druge promjene do dogovorenog roka.' },
      { title: 'Obračun i usklađivanje', body: 'Obračun se provodi u dogovorenom opsegu i povezuje s knjigovodstvom.' },
    ],
    faq: [
      { question: 'Koji su podaci potrebni za obračun plaća?', answer: 'Potrebni su matični podaci, početak zaposlenja, radno vrijeme, dogovorena plaća, bankovni podaci i mjesečne promjene.' },
      { question: 'Pomažete li pri prijavi i odjavi zaposlenika?', answer: 'Moguće prijave i rokovi moraju se dogovoriti prije početka. Potrebni podaci moraju biti dostavljeni pravodobno.' },
      { question: 'Mogu li mali poslodavci poslati upit?', answer: 'Mogu. Mogućnost preuzimanja ovisi o broju zaposlenika, stanju podataka i raspoloživom kapacitetu.' },
    ],
    ctaTitle: 'Razjasnite postupak obračuna plaća',
    ctaBody: 'Razgovaramo o broju zaposlenika, postojećoj dokumentaciji, rokovima predaje i potrebnom mjesečnom opsegu.',
    relatedLinkLabel: 'Uskladite obračun plaća i mjesečne podatke',
    related: ['/hr/knjigovodstvo-bec', '/hr/godisnji-obracun-bec', '/hr/porezno-savjetovanje-poduzetnici-bec'],
  },
  {
    path: '/hr/godisnji-obracun-bec',
    title: 'Godišnji obračun Beč | MINO Consulting KG',
    metaDescription: 'Godišnji obračun u Beču: usklađivanje knjigovodstva, završna dokumentacija, porezne prijave i razgovor o rezultatu.',
    eyebrow: 'Godišnji obračun Beč',
    h1: 'Priprema i razgovor o godišnjem obračunu u Beču',
    intro: 'Za godišnji obračun knjigovodstvo, konta i dodatni dokazi moraju biti potpuno usklađeni. Potrebni završni radovi i prijave ovise o pravnom obliku i poslovnoj godini.',
    whoForTitle: 'Uobičajene početne situacije',
    whoFor: ['Poslovna godina je završena i treba pripremiti završnu dokumentaciju', 'Konta, otvoreni računi ili imovina još nisu usklađeni', 'Za porezne prijave potrebni su zaključni podaci', 'Treba razgovarati o rezultatu i obvezama koje iz njega proizlaze'],
    includedTitle: 'Važni dijelovi godišnjeg obračuna',
    included: ['Pregled relevantne knjigovodstvene dokumentacije', 'Usklađivanje otvorenih stavki i računa', 'Pripremu izvještaja i zaključnih informacija', 'Razgovor o otvorenim pitanjima i sljedećim poreznim koracima'],
    clientProvides: ['Potpune knjigovodstvene, bankovne, blagajničke i imovinske podatke', 'Ugovore, inventuru, druge dokaze i pravodobne odgovore'],
    limitations: ['Dokumentacija i rokovi razlikuju se prema pravnom obliku i slučaju', 'Godišnji obračun nije revizija i tako se ne prikazuje'],
    processTitle: 'Tijek godišnjeg obračuna',
    process: [
      { title: 'Prikupljanje dokumentacije', body: 'Dogovaramo potrebne dokumente, popise i potvrde.' },
      { title: 'Usklađivanje', body: 'Otvorene stavke pregledavaju se i vraćaju na razjašnjenje.' },
      { title: 'Razgovor o rezultatu', body: 'Rezultat i sljedeće obveze objašnjavaju se u dogovorenom opsegu.' },
    ],
    faq: [
      { question: 'Koji su dokumenti potrebni za godišnji obračun?', answer: 'Ovisno o poduzeću, relevantni mogu biti knjigovodstveni podaci, bankovni izvodi, otvoreni računi, ugovori, imovina i dokumentacija o plaćama.' },
      { question: 'Kako izgleda priprema godišnjeg obračuna?', answer: 'Najprije se prikuplja i usklađuje dokumentacija, zatim se razjašnjavaju otvorena pitanja i razgovara o rezultatu.' },
      { question: 'Kada treba početi s pripremom?', answer: 'Dokumentaciju je korisno uređivati tijekom godine. Konkretan rok pripreme treba dogovoriti prema pravnom obliku, poslovnoj godini i stanju knjigovodstva.' },
    ],
    ctaTitle: 'Razjasnite dokumentaciju za godišnji obračun',
    ctaBody: 'Utvrđujemo stanje dokumentacije, otvorene točke i mogući način pripreme obračuna.',
    relatedLinkLabel: 'Pripremite godišnji obračun i završnu dokumentaciju',
    related: ['/hr/knjigovodstvo-bec', '/hr/porezni-savjetnik-bec', '/hr/obracun-placa-bec'],
  },
  {
    path: '/hr/porezno-savjetovanje-poduzetnici-bec',
    title: 'Porezno savjetovanje za poduzetnike Beč | MINO Consulting KG',
    metaDescription: 'Porezna i knjigovodstvena pitanja prije početka poslovanja u Beču: PDV, FinanzOnline, računi i prvi rokovi.',
    eyebrow: 'Porezno savjetovanje za poduzetnike',
    h1: 'Porezna pitanja prije početka poslovanja u Beču',
    intro: 'Prije početka javljaju se pitanja o pravnom obliku, PDV-u, računima, sustavu FinanzOnline i knjigovodstvu. MINO razmatra porezne i knjigovodstvene teme; pravne i javnobilježničke usluge odvojene su od toga.',
    whoForTitle: 'Uobičajeni razlozi za upit',
    whoFor: ['Planira se samostalna ili poduzetnička djelatnost', 'Izdavanje računa, PDV i FinanzOnline još nisu razjašnjeni', 'Nije uspostavljen postupak za dokumentaciju i knjigovodstvo', 'Treba razmotriti porezne razlike mogućih pravnih oblika'],
    includedTitle: 'Moguće teme prvog razgovora',
    included: ['Porezno razmatranje pravnog oblika, PDV-a i prvih rokova', 'Postavljanje knjigovodstva i dokumentacije', 'Pripremu za FinanzOnline i komunikaciju s tijelima', 'Pregled redovitih obveza nakon početka'],
    clientProvides: ['Opis djelatnosti, sudionika, početka te pretpostavke o prihodima i troškovima', 'Relevantne nacrte ugovora i pitanja o porezima i knjigovodstvu'],
    limitations: ['Opisuje se porezno i knjigovodstveno savjetovanje, ne pravna ili javnobilježnička usluga', 'Ne jamče se potpore, upisi ni odluke tijela'],
    processTitle: 'Od namjere do knjigovodstvenog početka',
    process: [
      { title: 'Opis namjere', body: 'Razgovaramo o djelatnosti, planiranom početku, prihodima, troškovima i pitanjima.' },
      { title: 'Razmatranje obveza', body: 'Porezne i knjigovodstvene teme razvrstavaju se prema dostavljenim podacima.' },
      { title: 'Dogovor o početku', body: 'Mogući budući opseg i način predaje dokumentacije dogovaraju se zasebno.' },
    ],
    faq: [
      { question: 'Kada prije osnivanja trebam zatražiti porezno savjetovanje?', answer: 'Razgovor je koristan prije konačnih odluka o računima, PDV-u i knjigovodstvu. Pravne i javnobilježničke korake treba dogovoriti s odgovarajućim stručnjacima.' },
      { question: 'Pomažete li pri FinanzOnlineu i prvim obvezama?', answer: 'Porezne obveze i mogući postupak u sustavu FinanzOnline mogu se razmotriti u dogovorenom opsegu.' },
      { question: 'Trebam li voditi dokumentaciju prije prvog prihoda?', answer: 'Troškovi i dokumenti mogu nastati prije prihoda. Koje evidencije konkretno trebate ovisi o djelatnosti i pravnom obliku.' },
    ],
    ctaTitle: 'Razgovarajte o poreznim pitanjima prije početka',
    ctaBody: 'Donesite opis namjere, pitanja i postojeću dokumentaciju kako bi se utvrdile teme koje treba razjasniti.',
    relatedLinkLabel: 'Razmotrite porezni početak i prve obveze',
    related: ['/hr/osnivanje-tvrtke-bec', '/hr/knjigovodstvo-bec', '/hr/obracun-placa-bec'],
  },
  {
    path: '/hr/osnivanje-tvrtke-bec',
    title: 'Osnivanje tvrtke Beč | MINO Consulting KG',
    metaDescription: 'Porezna pitanja i uspostava knjigovodstva pri osnivanju tvrtke u Beču, uz jasno odvajanje pravnih i javnobilježničkih usluga.',
    eyebrow: 'Osnivanje tvrtke Beč',
    h1: 'Knjigovodstvo i porezi pri osnivanju tvrtke u Beču',
    intro: 'Ova usluga odnosi se na porezno razmatranje i uspostavu knjigovodstva pri početku. Pravni, javnobilježnički i drugi pravni koraci obavljaju se kod za to ovlaštenih vanjskih stručnjaka.',
    whoForTitle: 'Uobičajene početne situacije',
    whoFor: ['Porezne posljedice planiranog osnivanja još nisu razjašnjene', 'Treba uspostaviti račune, predaju dokumenata i knjigovodstvo', 'Treba razmotriti prve porezne rokove i prijave', 'Kod planiranih zaposlenika treba pripremiti obračun plaća'],
    includedTitle: 'Što podrška može obuhvatiti',
    included: ['Porezno razmatranje planirane strukture', 'Postavljanje knjigovodstva i prvih poreznih obveza', 'Organizaciju dokumenata, računa i rokova', 'Razmatranje moguće redovite suradnje nakon osnivanja'],
    clientProvides: ['Opis namjere, sudionika, prihoda, troškova i financiranja', 'Stanje vanjskih koraka i pitanja o porezima i knjigovodstvu'],
    limitations: ['Nema savjetovanja o pravu društava ni javnobilježničkih usluga', 'Opseg usluge dogovara se tek nakon pregleda upita'],
    processTitle: 'Koraci porezne i knjigovodstvene pripreme',
    process: [
      { title: 'Razjašnjenje polazišta', body: 'Pregledavamo namjeru, djelatnost, sudionike i postojeću dokumentaciju.' },
      { title: 'Razmatranje strukture', body: 'Porezi, računi, knjigovodstvo i prve obveze razmatraju se u dogovorenom opsegu.' },
      { title: 'Dogovor o postupcima', body: 'Način predaje dokumentacije i moguća daljnja usluga određuju se zasebno.' },
    ],
    faq: [
      { question: 'Koje su porezne teme važne pri osnivanju tvrtke u Beču?', answer: 'Ovisno o slučaju, važni mogu biti pravni oblik, PDV, porez na dohodak ili dobit, izdavanje računa, dokumentacija i redoviti rokovi.' },
      { question: 'Mogu li zajedno razmotriti knjigovodstvo i osnivanje?', answer: 'Knjigovodstveni i porezni početak mogu se razmotriti zajedno. Pravne i javnobilježničke odluke ostaju kod ovlaštenih vanjskih stručnjaka.' },
      { question: 'Pružate li podršku i nakon osnivanja?', answer: 'Redovita suradnja može se zatražiti. Može li se i u kojem opsegu preuzeti, utvrđuje se nakon pregleda početne situacije.' },
    ],
    ctaTitle: 'Razjasnite porezni i knjigovodstveni početak',
    ctaBody: 'Na prvom razgovoru utvrđujemo koja su porezna i knjigovodstvena pitanja trenutačno važna i gdje su potrebni vanjski pravni stručnjaci.',
    relatedLinkLabel: 'Pripremite knjigovodstvo i poreze za osnivanje',
    related: ['/hr/porezno-savjetovanje-poduzetnici-bec', '/hr/knjigovodstvo-bec', '/hr/porezni-savjetnik-bec'],
  },
];
